# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -Duser.language=en -Duser.country=US -Duser.home=C:/Havamania-MobileApp/mobile/android/.user_home

# Windows Dosya Kilitleme Sorunu ?çin
org.gradle.daemon=true
org.gradle.vfs.watch=false

android.useAndroidX=true
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64
newArchEnabled=false
hermesEnabled=true

# Kotlin 2.0+ ve KSP Uyumlulu?u ?çin
kotlin.code.style=official
android.nonTransitiveRClass=false

# Gradle JDK 17 Configuration
org.gradle.java.home=C:/Program Files/Microsoft/jdk-17.0.18.8-hotspot
